### ISSUE TITLE
Saving a blog comment should redirect you to page of the post (SAKAI-3027)

### ISSUE THREAD

**Issue by davidpbauer** [UDayton/clog#1]
As a user of the blogs tool, I would like to immediately see my comment on a blog post after I save the comment so I can confirm that it was successfully saved in the spot I wanted. Right now when I save a comment, I'm redirected to the main page of the Blogs tool, and I need to return to the individual student's blog post to see the comment. This can be tasking if there are many blogs posts from which to choose. 

This video demonstrates this happening: 
http://screencast.com/t/xxiLbjJ0

**Comment by washingtonj3** [comment]
Refreshing or clicking any button of the same kind as the save, cancel, or delete buttons returns you to the home part of the tool.
