### ISSUE TITLE
Unclear how to see more authors in Blogs (SAKAI-3148)

### ISSUE THREAD

**Issue by davidpbauer** [UDayton/clog#3]
As an instructor, I would like to have some information indicating how to see more than 10 students' blogs in the Blogs tool. When you click on the Authors tab in Blogs, only the first 10 students load with no indication that you need to scroll down to the bottom of the page to load more. 

Either more students in the list should load when you first come to this page or there should be some text providing this information (see attached mockup).

![blogs scrolling text](https://cloud.githubusercontent.com/assets/4632527/19855466/1b44a532-9f4b-11e6-938c-610775911c6f.png)

**Comment by washingtonj3** [comment]
http://i.imgur.com/Clqv7IA.png
So would this be good?
